export const NetEvents = Object.freeze({
  OPEN: 'network:open',
  CLOSE: 'network:close',
  ERROR: 'network:error',
  MESSAGE: 'network:message',
  STATUS: 'network:status',
  JOIN: 'join',
  JOINED: 'joined',
  WELCOME: 'welcome',
  PEER_JOIN: 'peer-join',
  PEER_LEAVE: 'peer-leave',
  STATE: 'state',
  ACTION: 'action',
  WORLD_EVENT: 'world:event',
  LEADERBOARD_REQUEST: 'leaderboard:request',
  LEADERBOARD_SUBMIT: 'leaderboard:submit',
  LEADERBOARD_UPDATE: 'leaderboard:update',
  PING: 'ping',
  PONG: 'pong',
});
